var searchData=
[
  ['v_20pradinė_0',['Release v.pradinė',['../md__r_e_a_d_m_e.html#autotoc_md421',1,'']]],
  ['v0_201_1',['Release v0.1',['../md__r_e_a_d_m_e.html#autotoc_md422',1,'']]],
  ['v0_202_2',['Release v0.2',['../md__r_e_a_d_m_e.html#autotoc_md423',1,'']]],
  ['v0_203_3',['Release v0.3',['../md__r_e_a_d_m_e.html#autotoc_md424',1,'']]],
  ['v0_204_4',['Release v0.4',['../md__r_e_a_d_m_e.html#autotoc_md425',1,'']]],
  ['v1_200_5',['Release v1.0',['../md__r_e_a_d_m_e.html#autotoc_md431',1,'']]],
  ['v1_200_20initial_6',['Release v1.0-initial',['../md__r_e_a_d_m_e.html#autotoc_md426',1,'']]],
  ['validating_20a_20member_20of_20an_20object_7',['Validating a Member of an Object',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md138',1,'']]],
  ['validating_20the_20value_20pointed_20to_20by_20a_20pointer_20argument_8',['Validating the Value Pointed to by a Pointer Argument',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md139',1,'']]],
  ['value_9',['Returning a Value',['../md_build_2__deps_2googletest-src_2docs_2reference_2actions.html#autotoc_md245',1,'']]],
  ['value_10',['value',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#value',1,'']]],
  ['value_20for_20a_20return_20type_11',['Setting the Default Value for a Return Type',['../md_build_2__deps_2googletest-src_2docs_2reference_2mocking.html#DefaultValue',1,'']]],
  ['value_20not_20ignored_20as_20it_20ought_20to_20be_20what_20does_20this_20mean_12',['My compiler complains &quot;void value not ignored as it ought to be.&quot; What does this mean?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md92',1,'']]],
  ['value_20parameterized_20abstract_20tests_13',['Creating Value-Parameterized Abstract Tests',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md47',1,'']]],
  ['value_20parameterized_20test_20parameters_14',['Specifying Names for Value-Parameterized Test Parameters',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md48',1,'']]],
  ['value_20parameterized_20tests_15',['Value Parameterized Tests',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md46',1,'How to Write Value-Parameterized Tests'],['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md45',1,'Value-Parameterized Tests']]],
  ['value_20parameterized_20tests_16',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md87',1,'']]],
  ['value_20pointed_20to_20by_20a_20pointer_20argument_17',['Validating the Value Pointed to by a Pointer Argument',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md139',1,'']]],
  ['value_20what_20s_20going_20on_18',['My compiler complains that a constructor (or destructor) cannot return a value. What&apos;s going on?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md96',1,'']]],
  ['value_20when_20i_20call_20run_5fall_5ftests_20why_19',['My compiler complains about &quot;ignoring return value&quot; when I call RUN_ALL_TESTS(). Why?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md95',1,'']]],
  ['value_5fparam_20testinfo_3a_3avalue_5fparam_20',['value_param {TestInfo::value_param}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md309',1,'']]],
  ['values_21',['Values',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md181',1,'Teaching gMock How to Print Your Values'],['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md27',1,'Teaching GoogleTest How to Print Your Values']]],
  ['values_20exactly_22',['Matching Argument Values Exactly',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md130',1,'']]],
  ['values_20from_20mock_20methods_23',['Returning Live Values from Mock Methods',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md148',1,'']]],
  ['variables_24',['Why should I prefer test fixtures over global variables?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md100',1,'']]],
  ['variables_20but_20i_20did_20define_20them_20in_20the_20class_20body_20what_20s_20wrong_25',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md90',1,'']]],
  ['variadic_20function_26',['Can I mock a variadic function?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md185',1,'']]],
  ['various_20build_20systems_27',['Using GoogleTest from various build systems',['../md_build_2__deps_2googletest-src_2docs_2pkgconfig.html',1,'']]],
  ['verification_28',['Forcing a Verification',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md162',1,'']]],
  ['verifying_20and_20resetting_20a_20mock_29',['Verifying and Resetting a Mock',['../md_build_2__deps_2googletest-src_2docs_2gmock__cheat__sheet.html#autotoc_md115',1,'']]],
  ['verifying_20complex_20arguments_30',['Verifying Complex Arguments',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#SaveArgVerify',1,'']]],
  ['versija_201_201_31',['Versija 1.1.',['../md__r_e_a_d_m_e.html#autotoc_md435',1,'']]],
  ['versija_201_202_32',['Versija 1.2.',['../md__r_e_a_d_m_e.html#autotoc_md438',1,'']]],
  ['versija_201_205_33',['Versija 1.5.',['../md__r_e_a_d_m_e.html#autotoc_md441',1,'']]],
  ['versija_202_200_34',['Versija 2.0.',['../md__r_e_a_d_m_e.html#autotoc_md442',1,'']]],
  ['versija_203_200_35',['Versija 3.0.',['../md__r_e_a_d_m_e.html#autotoc_md443',1,'']]],
  ['version_36',['C++ Standard Version',['../dir_001a0f336d1d0a6c17b1be78e41a6b36.html#autotoc_md402',1,'']]],
  ['vidurkis_37',['vidurkis',['../md__r_e_a_d_m_e.html#autotoc_md432',1,'1 strategija (pateikiamas kelių testų laikų vidurkis)'],['../md__r_e_a_d_m_e.html#autotoc_md433',1,'2 strategija (pateikiamas kelių testų laikų vidurkis)'],['../md__r_e_a_d_m_e.html#autotoc_md434',1,'3 strategija (pateikiamas kelių testų laikų vidurkis)'],['../md__r_e_a_d_m_e.html#autotoc_md436',1,'Laiko matavimų lentelė (pateikiamas kelių testų laikų vidurkis)'],['../md__r_e_a_d_m_e.html#autotoc_md430',1,'Laiko matavimų vidurkis']]],
  ['virtual_20methods_38',['Mocking Non-virtual Methods',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#MockingNonVirtualMethods',1,'']]],
  ['vision_20into_20mock_20calls_39',['Gaining Super Vision into Mock Calls',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md165',1,'']]],
  ['visual_20c_20runs_20out_20of_20memory_20when_20compiling_20it_20what_20can_20i_20do_40',['I have a huge mock class, and Microsoft Visual C++ runs out of memory when compiling it. What can I do?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md201',1,'']]],
  ['visual_20studio_20dynamic_20vs_20static_20runtimes_41',['Visual Studio Dynamic vs Static Runtimes',['../dir_001a0f336d1d0a6c17b1be78e41a6b36.html#autotoc_md401',1,'']]],
  ['void_20value_20not_20ignored_20as_20it_20ought_20to_20be_20what_20does_20this_20mean_42',['My compiler complains &quot;void value not ignored as it ought to be.&quot; What does this mean?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md92',1,'']]],
  ['vs_20static_20runtimes_43',['Visual Studio Dynamic vs Static Runtimes',['../dir_001a0f336d1d0a6c17b1be78e41a6b36.html#autotoc_md401',1,'']]],
  ['vs_20unexpected_20calls_44',['Understanding Uninteresting vs Unexpected Calls',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#uninteresting-vs-unexpected',1,'']]]
];
