var searchData=
[
  ['random_5fseed_20unittest_3a_3arandom_5fseed_0',['random_seed {UnitTest::random_seed}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md320',1,'']]],
  ['real_20object_1',['Delegating Calls to a Real Object',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md127',1,'']]],
  ['real_20object_20is_20fine_20what_20can_20be_20wrong_2',['I get a heapcheck failure when using a mock object, but using a real object is fine. What can be wrong?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md191',1,'']]],
  ['real_20object_20is_20invoked_20instead_20what_20s_20the_20problem_3',['When I call a method on my mock object, the method for the real object is invoked instead. What&apos;s the problem?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md184',1,'']]],
  ['reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_4',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md193',1,'']]],
  ['recipes_20on_20using_20gmock_5',['Misc Recipes on Using gMock',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md159',1,'']]],
  ['recordproperty_20test_3a_3arecordproperty_6',['RecordProperty {Test::RecordProperty}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md286',1,'']]],
  ['redundant_7',['I have a failed test where gMock tells me TWICE that a particular expectation is not satisfied. Isn&apos;t this redundant?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md190',1,'']]],
  ['reference_8',['Reference',['../md_build_2__deps_2googletest-src_2docs_2reference_2actions.html',1,'Actions Reference'],['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html',1,'Assertions Reference'],['../md_build_2__deps_2googletest-src_2docs_2reference_2matchers.html',1,'Matchers Reference'],['../md_build_2__deps_2googletest-src_2docs_2reference_2mocking.html',1,'Mocking Reference'],['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html',1,'Testing Reference']]],
  ['references_20from_20mock_20methods_9',['Returning References from Mock Methods',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md147',1,'']]],
  ['references_20to_20some_20static_20const_20member_20variables_20but_20i_20did_20define_20them_20in_20the_20class_20body_20what_20s_20wrong_10',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md90',1,'']]],
  ['register_5ftyped_5ftest_5fsuite_5fp_11',['REGISTER_TYPED_TEST_SUITE_P',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#REGISTER_TYPED_TEST_SUITE_P',1,'']]],
  ['registering_20tests_20programmatically_12',['Registering tests programmatically',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md53',1,'']]],
  ['registertest_13',['RegisterTest',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#RegisterTest',1,'']]],
  ['regular_20expression_20syntax_14',['Regular Expression Syntax',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md28',1,'']]],
  ['related_20macros_3a_15',['Flag related macros:',['../dir_515acaf25bb6c3e95d5eef5219e6cc3f.html#autotoc_md383',1,'']]],
  ['related_20open_20source_20projects_16',['Related Open Source Projects',['../dir_b8d6b26144d6312ab7a4ea26f9e69ccf.html#autotoc_md418',1,'']]],
  ['release_201_2017_200_17',['Release 1.17.0',['../dir_b8d6b26144d6312ab7a4ea26f9e69ccf.html#autotoc_md410',1,'']]],
  ['release_20testeventlisteners_3a_3arelease_18',['Release {TestEventListeners::Release}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md354',1,'']]],
  ['release_20v_20pradinė_19',['Release v.pradinė',['../md__r_e_a_d_m_e.html#autotoc_md421',1,'']]],
  ['release_20v0_201_20',['Release v0.1',['../md__r_e_a_d_m_e.html#autotoc_md422',1,'']]],
  ['release_20v0_202_21',['Release v0.2',['../md__r_e_a_d_m_e.html#autotoc_md423',1,'']]],
  ['release_20v0_203_22',['Release v0.3',['../md__r_e_a_d_m_e.html#autotoc_md424',1,'']]],
  ['release_20v0_204_23',['Release v0.4',['../md__r_e_a_d_m_e.html#autotoc_md425',1,'']]],
  ['release_20v1_200_24',['Release v1.0',['../md__r_e_a_d_m_e.html#autotoc_md431',1,'']]],
  ['release_20v1_200_20initial_25',['Release v1.0-initial',['../md__r_e_a_d_m_e.html#autotoc_md426',1,'']]],
  ['repeating_20the_20tests_26',['Repeating the Tests',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md68',1,'']]],
  ['report_27',['Report',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md77',1,'Generating a JSON Report'],['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md76',1,'Generating an XML Report']]],
  ['reportable_5fdisabled_5ftest_5fcount_20testsuite_3a_3areportable_5fdisabled_5ftest_5fcount_28',['reportable_disabled_test_count {TestSuite::reportable_disabled_test_count}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md295',1,'']]],
  ['reportable_5fdisabled_5ftest_5fcount_20unittest_3a_3areportable_5fdisabled_5ftest_5fcount_29',['reportable_disabled_test_count {UnitTest::reportable_disabled_test_count}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md328',1,'']]],
  ['reportable_5ftest_5fcount_20testsuite_3a_3areportable_5ftest_5fcount_30',['reportable_test_count {TestSuite::reportable_test_count}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md297',1,'']]],
  ['reportable_5ftest_5fcount_20unittest_3a_3areportable_5ftest_5fcount_31',['reportable_test_count {UnitTest::reportable_test_count}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md330',1,'']]],
  ['reported_32',['Controlling How Failures Are Reported',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md78',1,'']]],
  ['require_20the_20entire_20test_20suite_20instead_20of_20individual_20tests_20to_20be_20named_20deathtest_20when_20it_20uses_20assert_5fdeath_33',['Why does GoogleTest require the entire test suite, instead of individual tests, to be named &lt;span class=&quot;tt&quot;&gt;*DeathTest&lt;/span&gt; when it uses &lt;span class=&quot;tt&quot;&gt;ASSERT_DEATH&lt;/span&gt;?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md103',1,'']]],
  ['requirements_20for_20contributors_34',['Requirements for Contributors',['../md_build_2__deps_2googletest-src_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md7',1,'']]],
  ['requirements_20should_20i_20use_20typed_20tests_20or_20value_20parameterized_20tests_35',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md87',1,'']]],
  ['resetting_20a_20mock_36',['Verifying and Resetting a Mock',['../md_build_2__deps_2googletest-src_2docs_2gmock__cheat__sheet.html#autotoc_md115',1,'']]],
  ['resources_20between_20tests_20in_20the_20same_20test_20suite_37',['Sharing Resources Between Tests in the Same Test Suite',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md43',1,'']]],
  ['restricting_20the_20type_20of_20an_20argument_20or_20parameter_20in_20an_20action_38',['Restricting the Type of an Argument or Parameter in an ACTION',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md178',1,'']]],
  ['result_39',['Ignoring an Action&apos;s Result',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md155',1,'']]],
  ['result_20of_20a_20function_20functor_20or_20callback_40',['Matching the Result of a Function, Functor, or Callback',['../md_build_2__deps_2googletest-src_2docs_2reference_2matchers.html#autotoc_md259',1,'']]],
  ['result_20testinfo_3a_3aresult_41',['result {TestInfo::result}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md315',1,'']]],
  ['retires_42',['Controlling When an Expectation Retires',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md145',1,'']]],
  ['retiresonsaturation_43',['RetiresOnSaturation {EXPECT_CALL.RetiresOnSaturation}',['../md_build_2__deps_2googletest-src_2docs_2reference_2mocking.html#autotoc_md271',1,'']]],
  ['retiresonsaturation_20expect_5fcall_20retiresonsaturation_44',['RetiresOnSaturation {EXPECT_CALL.RetiresOnSaturation}',['../md_build_2__deps_2googletest-src_2docs_2reference_2mocking.html#autotoc_md271',1,'']]],
  ['return_20a_20value_20what_20s_20going_20on_45',['My compiler complains that a constructor (or destructor) cannot return a value. What&apos;s going on?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md96',1,'']]],
  ['return_20type_46',['Setting the Default Value for a Return Type',['../md_build_2__deps_2googletest-src_2docs_2reference_2mocking.html#DefaultValue',1,'']]],
  ['return_20type_20specified_20what_20does_20it_20mean_47',['I use SetArgPointee() in WillOnce(), but gcc complains about &quot;conflicting return type specified&quot;. What does it mean?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md200',1,'']]],
  ['return_20value_20when_20i_20call_20run_5fall_5ftests_20why_48',['My compiler complains about &quot;ignoring return value&quot; when I call RUN_ALL_TESTS(). Why?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md95',1,'']]],
  ['returning_20a_20value_49',['Returning a Value',['../md_build_2__deps_2googletest-src_2docs_2reference_2actions.html#autotoc_md245',1,'']]],
  ['returning_20live_20values_20from_20mock_20methods_50',['Returning Live Values from Mock Methods',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md148',1,'']]],
  ['returning_20references_20from_20mock_20methods_51',['Returning References from Mock Methods',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md147',1,'']]],
  ['returns_20an_20assertionresult_52',['Using a Function That Returns an AssertionResult',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md17',1,'']]],
  ['routines_53',['Using Assertions in Sub-routines',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md36',1,'']]],
  ['rule_20makes_20writing_20expectations_20awkward_20why_20does_20gmock_20do_20that_54',['The &quot;newer expectations override older ones&quot; rule makes writing expectations awkward. Why does gMock do that?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md192',1,'']]],
  ['run_20a_20binary_55',['run a binary',['../md_build_2__deps_2googletest-src_2docs_2quickstart-bazel.html#autotoc_md237',1,'Create and run a binary'],['../md_build_2__deps_2googletest-src_2docs_2quickstart-cmake.html#autotoc_md242',1,'Create and run a binary']]],
  ['run_5fall_5ftests_56',['RUN_ALL_TESTS',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#RUN_ALL_TESTS',1,'']]],
  ['run_5fall_5ftests_20why_57',['My compiler complains about &quot;ignoring return value&quot; when I call RUN_ALL_TESTS(). Why?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md95',1,'']]],
  ['running_20a_20subset_20of_20the_20tests_58',['Running a Subset of the Tests',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md62',1,'']]],
  ['running_20at_20least_20one_20test_20case_59',['Enforcing Running At Least One Test Case',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md67',1,'']]],
  ['running_20in_20a_20test_60',['How can my code detect if it is running in a test?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md108',1,'']]],
  ['running_20test_20programs_3a_20advanced_20options_61',['Running Test Programs: Advanced Options',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md59',1,'']]],
  ['running_20tests_20in_20emacs_62',['Running Tests in Emacs',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md166',1,'']]],
  ['runs_20out_20of_20memory_20when_20compiling_20it_20what_20can_20i_20do_63',['I have a huge mock class, and Microsoft Visual C++ runs out of memory when compiling it. What can I do?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md201',1,'']]],
  ['runtimes_64',['Visual Studio Dynamic vs Static Runtimes',['../dir_001a0f336d1d0a6c17b1be78e41a6b36.html#autotoc_md401',1,'']]]
];
