var searchData=
[
  ['each_20of_20them_20this_20seems_20pretty_20tedious_0',['I have several test suites which share the same test fixture logic; do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md98',1,'']]],
  ['effects_1',['Effects',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#MockingSideEffects',1,'Mocking Side Effects'],['../md_build_2__deps_2googletest-src_2docs_2reference_2actions.html#autotoc_md246',1,'Side Effects']]],
  ['effects_2',['Matchers must have no side-effects',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#PureMatchers',1,'']]],
  ['elapsed_20time_3',['Suppressing the Elapsed Time',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md74',1,'']]],
  ['elapsed_5ftime_20testresult_3a_3aelapsed_5ftime_4',['elapsed_time {TestResult::elapsed_time}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md374',1,'']]],
  ['elapsed_5ftime_20testsuite_3a_3aelapsed_5ftime_5',['elapsed_time {TestSuite::elapsed_time}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md302',1,'']]],
  ['elapsed_5ftime_20unittest_3a_3aelapsed_5ftime_6',['elapsed_time {UnitTest::elapsed_time}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md334',1,'']]],
  ['emacs_7',['Running Tests in Emacs',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md166',1,'']]],
  ['emptytesteventlistener_8',['EmptyTestEventListener',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#EmptyTestEventListener',1,'']]],
  ['enabling_20disabled_20tests_9',['Temporarily Enabling Disabled Tests',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md65',1,'']]],
  ['encountered_20default_20action_20taken_20should_20i_20panic_10',['I got a warning &quot;Uninteresting function call encountered - default action taken..&quot; Should I panic?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md198',1,'']]],
  ['enforcing_20having_20at_20least_20one_20test_20case_11',['Enforcing Having At Least One Test Case',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md66',1,'']]],
  ['enforcing_20running_20at_20least_20one_20test_20case_12',['Enforcing Running At Least One Test Case',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md67',1,'']]],
  ['entire_20test_20suite_20deathtest_20when_20it_20contains_20both_20death_20tests_20and_20non_20death_20tests_20what_20do_20i_20do_13',['But I don&apos;t like calling my entire test suite &lt;span class=&quot;tt&quot;&gt;*DeathTest&lt;/span&gt; when it contains both death tests and non-death tests. What do I do?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md104',1,'']]],
  ['entire_20test_20suite_20instead_20of_20individual_20tests_20to_20be_20named_20deathtest_20when_20it_20uses_20assert_5fdeath_14',['Why does GoogleTest require the entire test suite, instead of individual tests, to be named &lt;span class=&quot;tt&quot;&gt;*DeathTest&lt;/span&gt; when it uses &lt;span class=&quot;tt&quot;&gt;ASSERT_DEATH&lt;/span&gt;?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md103',1,'']]],
  ['environment_15',['Environment',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#Environment',1,'']]],
  ['environment_3a_3asetup_16',['SetUp {Environment::SetUp}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md278',1,'']]],
  ['environment_3a_3ateardown_17',['TearDown {Environment::TearDown}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md279',1,'']]],
  ['error_20messages_18',['Predicate Assertions for Better Error Messages',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md15',1,'']]],
  ['error_20no_20matching_20function_20for_20call_20to_20footest_3a_3afootest_20why_19',['I have a fixture class &lt;span class=&quot;tt&quot;&gt;FooTest&lt;/span&gt;, but &lt;span class=&quot;tt&quot;&gt;TEST_F(FooTest, Bar)&lt;/span&gt; gives me error &lt;span class=&quot;tt&quot;&gt;&quot;no matching function for call to `FooTestFooTest()&apos;&quot;&lt;/span&gt;. Why?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md102',1,'']]],
  ['errors_20in_20opt_20mode_20is_20this_20a_20googletest_20bug_20',['EXPECT_EQ(htonl(blah), blah_blah) generates weird compiler errors in opt mode. Is this a GoogleTest bug?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md89',1,'']]],
  ['even_20if_20i_20have_20set_20its_20behavior_20using_20on_5fcall_20would_20it_20be_20reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_21',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md193',1,'']]],
  ['event_20listeners_22',['Event Listeners',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md56',1,'Defining Event Listeners'],['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md57',1,'Using Event Listeners']]],
  ['events_23',['Extending GoogleTest by Handling Test Events',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md55',1,'']]],
  ['exactly_24',['Matching Argument Values Exactly',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md130',1,'']]],
  ['example_25',['Basic Example',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md168',1,'']]],
  ['exception_26',['Asserting on Subroutines with an exception',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md39',1,'']]],
  ['exception_20assertions_27',['Exception Assertions',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md14',1,'Exception Assertions'],['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#exceptions',1,'Exception Assertions']]],
  ['exception_20matchers_28',['Exception Matchers',['../md_build_2__deps_2googletest-src_2docs_2reference_2matchers.html#autotoc_md256',1,'']]],
  ['exceptions_29',['Disabling Catching Test-Thrown Exceptions',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md81',1,'']]],
  ['exe_20failų_20dydžių_20lentelė_30',['exe failų dydžių lentelė',['../md__r_e_a_d_m_e.html#autotoc_md437',1,'']]],
  ['execution_31',['Skipping test execution',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md26',1,'']]],
  ['execution_20upon_20first_20failure_32',['Stop test execution upon first failure',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md63',1,'']]],
  ['existing_20boolean_20function_33',['Using an Existing Boolean Function',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md16',1,'']]],
  ['existing_20cmake_20project_34',['Incorporating Into An Existing CMake Project',['../dir_001a0f336d1d0a6c17b1be78e41a6b36.html#autotoc_md400',1,'']]],
  ['existing_20code_35',['Simplifying the Interface without Breaking Existing Code',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#SimplerInterfaces',1,'']]],
  ['exit_36',['Detecting Test Premature Exit',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md79',1,'']]],
  ['expect_37',['Expect',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#UseOnCall',1,'Knowing When to Expect'],['../md_build_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#autotoc_md214',1,'Matchers: What Arguments Do We Expect?']]],
  ['expect_5f_20statements_20in_20matchers_38',['Using EXPECT_ Statements in Matchers',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md170',1,'']]],
  ['expect_5fany_5fthrow_39',['EXPECT_ANY_THROW',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_ANY_THROW',1,'']]],
  ['expect_5fcall_40',['EXPECT_CALL',['../md_build_2__deps_2googletest-src_2docs_2reference_2mocking.html#EXPECT_CALL',1,'']]],
  ['expect_5fcall_20after_41',['After {EXPECT_CALL.After}',['../md_build_2__deps_2googletest-src_2docs_2reference_2mocking.html#autotoc_md268',1,'']]],
  ['expect_5fcall_20insequence_42',['InSequence {EXPECT_CALL.InSequence}',['../md_build_2__deps_2googletest-src_2docs_2reference_2mocking.html#autotoc_md267',1,'']]],
  ['expect_5fcall_20is_20called_20even_20if_20i_20have_20set_20its_20behavior_20using_20on_5fcall_20would_20it_20be_20reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_43',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md193',1,'']]],
  ['expect_5fcall_20retiresonsaturation_44',['RetiresOnSaturation {EXPECT_CALL.RetiresOnSaturation}',['../md_build_2__deps_2googletest-src_2docs_2reference_2mocking.html#autotoc_md271',1,'']]],
  ['expect_5fcall_20times_45',['Times {EXPECT_CALL.Times}',['../md_build_2__deps_2googletest-src_2docs_2reference_2mocking.html#autotoc_md266',1,'']]],
  ['expect_5fcall_20willonce_46',['WillOnce {EXPECT_CALL.WillOnce}',['../md_build_2__deps_2googletest-src_2docs_2reference_2mocking.html#autotoc_md269',1,'']]],
  ['expect_5fcall_20willrepeatedly_47',['WillRepeatedly {EXPECT_CALL.WillRepeatedly}',['../md_build_2__deps_2googletest-src_2docs_2reference_2mocking.html#autotoc_md270',1,'']]],
  ['expect_5fcall_20with_48',['With {EXPECT_CALL.With}',['../md_build_2__deps_2googletest-src_2docs_2reference_2mocking.html#autotoc_md265',1,'']]],
  ['expect_5fdeath_49',['EXPECT_DEATH',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_DEATH',1,'']]],
  ['expect_5fdeath_5fif_5fsupported_50',['EXPECT_DEATH_IF_SUPPORTED',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_DEATH_IF_SUPPORTED',1,'']]],
  ['expect_5fdebug_5fdeath_51',['EXPECT_DEBUG_DEATH',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_DEBUG_DEATH',1,'']]],
  ['expect_5fdouble_5feq_52',['EXPECT_DOUBLE_EQ',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_DOUBLE_EQ',1,'']]],
  ['expect_5feq_53',['EXPECT_EQ',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_EQ',1,'']]],
  ['expect_5feq_20htonl_20blah_20blah_5fblah_20generates_20weird_20compiler_20errors_20in_20opt_20mode_20is_20this_20a_20googletest_20bug_54',['EXPECT_EQ(htonl(blah), blah_blah) generates weird compiler errors in opt mode. Is this a GoogleTest bug?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md89',1,'']]],
  ['expect_5feq_20null_20ptr_20and_20assert_5feq_20null_20ptr_20but_20not_20expect_5fne_20null_20ptr_20and_20assert_5fne_20null_20ptr_55',['Why does GoogleTest support &lt;span class=&quot;tt&quot;&gt;EXPECT_EQ(NULL, ptr)&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;ASSERT_EQ(NULL, ptr)&lt;/span&gt; but not &lt;span class=&quot;tt&quot;&gt;EXPECT_NE(NULL, ptr)&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;ASSERT_NE(NULL, ptr)&lt;/span&gt;?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md86',1,'']]],
  ['expect_5fexit_56',['EXPECT_EXIT',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_EXIT',1,'']]],
  ['expect_5ffalse_57',['EXPECT_FALSE',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_FALSE',1,'']]],
  ['expect_5ffloat_5feq_58',['EXPECT_FLOAT_EQ',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_FLOAT_EQ',1,'']]],
  ['expect_5fge_59',['EXPECT_GE',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_GE',1,'']]],
  ['expect_5fgt_60',['EXPECT_GT',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_GT',1,'']]],
  ['expect_5fhresult_5ffailed_61',['EXPECT_HRESULT_FAILED',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_HRESULT_FAILED',1,'']]],
  ['expect_5fhresult_5fsucceeded_62',['EXPECT_HRESULT_SUCCEEDED',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_HRESULT_SUCCEEDED',1,'']]],
  ['expect_5fle_63',['EXPECT_LE',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_LE',1,'']]],
  ['expect_5flt_64',['EXPECT_LT',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_LT',1,'']]],
  ['expect_5fne_65',['EXPECT_NE',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_NE',1,'']]],
  ['expect_5fne_20null_20ptr_20and_20assert_5fne_20null_20ptr_66',['Why does GoogleTest support &lt;span class=&quot;tt&quot;&gt;EXPECT_EQ(NULL, ptr)&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;ASSERT_EQ(NULL, ptr)&lt;/span&gt; but not &lt;span class=&quot;tt&quot;&gt;EXPECT_NE(NULL, ptr)&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;ASSERT_NE(NULL, ptr)&lt;/span&gt;?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md86',1,'']]],
  ['expect_5fnear_67',['EXPECT_NEAR',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_NEAR',1,'']]],
  ['expect_5fno_5fthrow_68',['EXPECT_NO_THROW',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_NO_THROW',1,'']]],
  ['expect_5fpred_69',['EXPECT_PRED*',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_PRED',1,'']]],
  ['expect_5fpred_5fformat_70',['EXPECT_PRED_FORMAT*',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_PRED_FORMAT',1,'']]],
  ['expect_5fstrcaseeq_71',['EXPECT_STRCASEEQ',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_STRCASEEQ',1,'']]],
  ['expect_5fstrcasene_72',['EXPECT_STRCASENE',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_STRCASENE',1,'']]],
  ['expect_5fstreq_73',['EXPECT_STREQ',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_STREQ',1,'']]],
  ['expect_5fstrne_74',['EXPECT_STRNE',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_STRNE',1,'']]],
  ['expect_5fthat_75',['EXPECT_THAT',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_THAT',1,'']]],
  ['expect_5fthrow_76',['EXPECT_THROW',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_THROW',1,'']]],
  ['expect_5ftrue_77',['EXPECT_TRUE',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_TRUE',1,'']]],
  ['expectation_78',['Expectation',['../md_build_2__deps_2googletest-src_2docs_2reference_2mocking.html#Expectation',1,'']]],
  ['expectation_20is_20not_20satisfied_20isn_20t_20this_20redundant_79',['I have a failed test where gMock tells me TWICE that a particular expectation is not satisfied. Isn&apos;t this redundant?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md190',1,'']]],
  ['expectation_20order_80',['Expectation Order',['../md_build_2__deps_2googletest-src_2docs_2gmock__cheat__sheet.html#autotoc_md114',1,'']]],
  ['expectation_20ordering_81',['Expectation Ordering',['../md_build_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#autotoc_md211',1,'']]],
  ['expectation_20retires_82',['Controlling When an Expectation Retires',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md145',1,'']]],
  ['expectations_83',['Expectations',['../md_build_2__deps_2googletest-src_2docs_2gmock__cheat__sheet.html#ExpectCall',1,'Setting Expectations'],['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md142',1,'Setting Expectations'],['../md_build_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#autotoc_md212',1,'Setting Expectations'],['../md_build_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#MultiExpectations',1,'Using Multiple Expectations']]],
  ['expectations_20are_20not_20satisfied_20what_20should_20i_20do_84',['I can&apos;t figure out why gMock thinks my expectations are not satisfied. What should I do?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md187',1,'']]],
  ['expectations_20are_20sticky_20unless_20said_20otherwise_85',['All Expectations Are Sticky (Unless Said Otherwise)',['../md_build_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#StickyExpectations',1,'']]],
  ['expectations_20awkward_20why_20does_20gmock_20do_20that_86',['The &quot;newer expectations override older ones&quot; rule makes writing expectations awkward. Why does gMock do that?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md192',1,'']]],
  ['expectations_20override_20older_20ones_20rule_20makes_20writing_20expectations_20awkward_20why_20does_20gmock_20do_20that_87',['The &quot;newer expectations override older ones&quot; rule makes writing expectations awkward. Why does gMock do that?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md192',1,'']]],
  ['expectationset_88',['ExpectationSet',['../md_build_2__deps_2googletest-src_2docs_2reference_2mocking.html#ExpectationSet',1,'']]],
  ['expecting_20ordered_20calls_89',['Expecting Ordered Calls',['../md_build_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#OrderedCalls',1,'']]],
  ['expecting_20partially_20ordered_20calls_90',['Expecting Partially Ordered Calls',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#PartialOrder',1,'']]],
  ['explicit_20success_20and_20failure_91',['Explicit Success and Failure',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md13',1,'Explicit Success and Failure'],['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#success-failure',1,'Explicit Success and Failure']]],
  ['exporting_20api_20symbols_3a_92',['Exporting API symbols:',['../dir_1d775d305344cfd1bbc62e0179de2c96.html#autotoc_md394',1,'']]],
  ['expression_20syntax_93',['Regular Expression Syntax',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md28',1,'']]],
  ['extending_20gmock_94',['Extending gMock',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md167',1,'']]],
  ['extending_20googletest_20by_20handling_20test_20events_95',['Extending GoogleTest by Handling Test Events',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md55',1,'']]],
  ['extra_20info_20as_20actions_96',['Using Functions with Extra Info as Actions',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md152',1,'']]]
];
