var searchData=
[
  ['laikų_20vidurkis_0',['laikų vidurkis',['../md__r_e_a_d_m_e.html#autotoc_md432',1,'1 strategija (pateikiamas kelių testų laikų vidurkis)'],['../md__r_e_a_d_m_e.html#autotoc_md433',1,'2 strategija (pateikiamas kelių testų laikų vidurkis)'],['../md__r_e_a_d_m_e.html#autotoc_md434',1,'3 strategija (pateikiamas kelių testų laikų vidurkis)'],['../md__r_e_a_d_m_e.html#autotoc_md436',1,'Laiko matavimų lentelė (pateikiamas kelių testų laikų vidurkis)']]],
  ['laiko_20matavimų_20lentelė_1',['Laiko matavimų lentelė',['../md__r_e_a_d_m_e.html#autotoc_md428',1,'']]],
  ['laiko_20matavimų_20lentelė_20pateikiamas_20kelių_20testų_20laikų_20vidurkis_2',['Laiko matavimų lentelė (pateikiamas kelių testų laikų vidurkis)',['../md__r_e_a_d_m_e.html#autotoc_md436',1,'']]],
  ['laiko_20matavimų_20vidurkis_3',['Laiko matavimų vidurkis',['../md__r_e_a_d_m_e.html#autotoc_md430',1,'']]],
  ['lambda_20as_20an_20action_4',['Using a Function, Functor, or Lambda as an Action',['../md_build_2__deps_2googletest-src_2docs_2reference_2actions.html#autotoc_md247',1,'']]],
  ['lambda_20callback_20without_20arguments_5',['Invoking a Function/Method/Functor/Lambda/Callback Without Arguments',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md153',1,'']]],
  ['lambdas_20as_20actions_6',['Using Functions/Methods/Functors/Lambdas as Actions',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#FunctionsAsActions',1,'']]],
  ['leak_20messages_20on_20windows_7',['How do I suppress the memory leak messages on Windows?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md107',1,'']]],
  ['least_20one_20test_20case_8',['Least One Test Case',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md66',1,'Enforcing Having At Least One Test Case'],['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md67',1,'Enforcing Running At Least One Test Case']]],
  ['legacy_20gmock_20faq_9',['Legacy gMock FAQ',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html',1,'']]],
  ['legacy_20macro_20based_20actions_10',['Legacy macro-based Actions',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md176',1,'']]],
  ['legacy_20macro_20based_20parameterized_20actions_11',['Legacy macro-based parameterized Actions',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md177',1,'']]],
  ['legacy_20matcher_20implementation_12',['Legacy Matcher Implementation',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md174',1,'']]],
  ['legacy_20workarounds_20for_20move_20only_20types_13',['Legacy workarounds for move-only types',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#LegacyMoveOnly',1,'']]],
  ['lentelė_14',['lentelė',['../md__r_e_a_d_m_e.html#autotoc_md437',1,'exe failų dydžių lentelė'],['../md__r_e_a_d_m_e.html#autotoc_md428',1,'Laiko matavimų lentelė'],['../md__r_e_a_d_m_e.html#autotoc_md429',1,'Pakartotinų matavimų lentelė']]],
  ['lentelė_20pateikiamas_20kelių_20testų_20laikų_20vidurkis_15',['Laiko matavimų lentelė (pateikiamas kelių testų laikų vidurkis)',['../md__r_e_a_d_m_e.html#autotoc_md436',1,'']]],
  ['library_20dll_16',['As a Shared Library (DLL)',['../dir_001a0f336d1d0a6c17b1be78e41a6b36.html#autotoc_md405',1,'']]],
  ['library_20support_20features_17',['Underlying library support features',['../dir_1d775d305344cfd1bbc62e0179de2c96.html#autotoc_md393',1,'']]],
  ['license_20agreements_18',['Contributor License Agreements',['../md_build_2__deps_2googletest-src_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md1',1,'']]],
  ['like_20calling_20my_20entire_20test_20suite_20deathtest_20when_20it_20contains_20both_20death_20tests_20and_20non_20death_20tests_20what_20do_20i_20do_19',['But I don&apos;t like calling my entire test suite &lt;span class=&quot;tt&quot;&gt;*DeathTest&lt;/span&gt; when it contains both death tests and non-death tests. What do I do?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md104',1,'']]],
  ['limitations_20',['Known Limitations',['../md_build_2__deps_2googletest-src_2docs_2primer.html#autotoc_md233',1,'']]],
  ['line_20testinfo_3a_3aline_21',['line {TestInfo::line}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md311',1,'']]],
  ['line_5fnumber_20testpartresult_3a_3aline_5fnumber_22',['line_number {TestPartResult::line_number}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md359',1,'']]],
  ['listeners_23',['Listeners',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md56',1,'Defining Event Listeners'],['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md58',1,'Generating Failures in Listeners'],['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md57',1,'Using Event Listeners']]],
  ['listeners_20unittest_3a_3alisteners_24',['listeners {UnitTest::listeners}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md339',1,'']]],
  ['listing_20test_20names_25',['Listing Test Names',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md61',1,'']]],
  ['live_20values_20from_20mock_20methods_26',['Returning Live Values from Mock Methods',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md148',1,'']]],
  ['log_20messages_20in_20a_20death_20test_20s_20child_20process_20only_20when_20the_20test_20fails_20how_20can_20i_20see_20the_20log_20messages_20when_20the_20death_20test_20succeeds_27',['GoogleTest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md105',1,'']]],
  ['log_20messages_20what_20do_20i_20do_28',['GoogleTest output is buried in a whole bunch of LOG messages. What do I do?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md99',1,'']]],
  ['log_20messages_20when_20the_20death_20test_20succeeds_29',['GoogleTest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md105',1,'']]],
  ['logging_20additional_20information_30',['Logging Additional Information',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md42',1,'']]],
  ['logging_3a_31',['Logging:',['../dir_1d775d305344cfd1bbc62e0179de2c96.html#autotoc_md391',1,'']]],
  ['logic_20do_20i_20have_20to_20define_20a_20new_20test_20fixture_20class_20for_20each_20of_20them_20this_20seems_20pretty_20tedious_32',['I have several test suites which share the same test fixture logic; do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md98',1,'']]],
  ['lost_20after_20the_20death_20test_20finishes_20why_33',['My death test modifies some state, but the change seems lost after the death test finishes. Why?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md88',1,'']]],
  ['lot_20of_20pain_20to_20specify_20the_20actions_20gmock_20sucks_34',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md197',1,'']]]
];
